global:
  scrape_interval: 5s

rule_files:
  - "/etc/prometheus/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

scrape_configs:
  - job_name: 'guardian-ai'
    static_configs:
      - targets: ['ai-detection:8000']

  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy-lb1:80', 'haproxy-lb2:80', 'haproxy-lb3:80']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend-api1:5000', 'backend-api2:5000', 'backend-api3:5000']
